# Generated by Django 5.1.2 on 2026-07-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_planactionmember'),
        ('users', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plans_action',
            field=models.ManyToManyField(blank=True, related_name='participants', through='planning.PlanActionMember', to='planning.planaction', verbose_name="Plans d'action"),
        ),
    ]
