# Generated by Django 5.1.2 on 2026-07-03 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Action',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('titre', models.CharField(max_length=500)),
                        ('couts', models.JSONField(default=list)),
                        ('nombre_activites', models.PositiveIntegerField(default=0)),
                        ('reference', models.CharField(blank=True, max_length=50)),
                    ],
                    options={
                        'verbose_name': 'Action',
                        'verbose_name_plural': 'Actions',
                    },
                ),
                migrations.CreateModel(
                    name='Organization',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255, verbose_name='Nom')),
                        ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                        ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('trial', 'Essai')], default='active', max_length=20, verbose_name='Statut')),
                        ('branding', models.JSONField(blank=True, default=dict, help_text='Logo, couleurs, nom affiché, etc.', verbose_name='Configuration visuelle')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                    ],
                    options={
                        'verbose_name': 'Organisation',
                        'verbose_name_plural': 'Organisations',
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='Activite',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('reference', models.CharField(blank=True, max_length=50)),
                        ('titre', models.CharField(max_length=500)),
                        ('type', models.CharField(choices=[('Réforme', 'Réforme'), ('Investissement', 'Investissement'), ('Etude', 'Etude'), ('Texte', 'Texte'), ('Activité ordinaire', 'Activité ordinaire')], max_length=50)),
                        ('structure', models.CharField(blank=True, choices=[('DGI', 'DGI'), ('DGD', 'DGD'), ('DGTCP', 'DGTCP'), ('DGMP', 'DGMP'), ('DGF', 'DGF'), ('DGBF', 'DGBF'), ('DGE', 'DGE')], default='', max_length=50)),
                        ('indicateur_label', models.CharField(max_length=500)),
                        ('indicateur_reference', models.CharField(max_length=500)),
                        ('cibles', models.JSONField(default=list)),
                        ('realisation', models.JSONField(default=list)),
                        ('couts', models.JSONField(default=list)),
                        ('periodes_execution', models.JSONField(default=list)),
                        ('etat_avancement', models.JSONField(default=list)),
                        ('commentaire', models.JSONField(default=list)),
                        ('commentaire_se', models.JSONField(default=list)),
                        ('pending_changes', models.JSONField(default=list)),
                        ('proposed_changes', models.JSONField(default=list)),
                        ('status', models.JSONField(default=list)),
                        ('matrix_status', models.JSONField(default=list)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('alertes_envoyees', models.JSONField(blank=True, default=dict, null=True)),
                        ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_activite', to='planning.action')),
                        ('point_focal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_focal_activites', to=settings.AUTH_USER_MODEL)),
                        ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_activites', to=settings.AUTH_USER_MODEL)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='planning.organization', verbose_name='Organisation')),
                    ],
                    options={
                        'verbose_name': 'Activité',
                        'verbose_name_plural': 'Activités',
                    },
                ),
                migrations.CreateModel(
                    name='Domain',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('domain', models.CharField(db_index=True, help_text='Exemple : dpse.mfb.gouv.ci ou app.aidn.ci', max_length=253, unique=True, verbose_name='Domaine')),
                        ('is_primary', models.BooleanField(default=False, help_text='Domaine principal utilisé pour les liens et emails', verbose_name='Domaine principal')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='planning.organization', verbose_name='Organisation')),
                    ],
                    options={
                        'verbose_name': 'Domaine',
                        'verbose_name_plural': 'Domaines',
                        'ordering': ['-is_primary', 'domain'],
                    },
                ),
                migrations.CreateModel(
                    name='ActiviteLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('modifications', models.JSONField()),
                        ('statut_apres', models.CharField(choices=[('Non évaluée', 'Non évaluée'), ('En cours', 'En cours'), ('Réalisée', 'Réalisée'), ('Non réalisée', 'Non réalisée'), ('Supprimée', 'Supprimée'), ('Reprogrammée', 'Reprogrammée')], max_length=50)),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='planning.activite')),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='planning.organization', verbose_name='Organisation')),
                    ],
                    options={
                        'verbose_name': "Journal d'activité",
                        'verbose_name_plural': "Journaux d'activités",
                        'ordering': ['-timestamp'],
                    },
                ),
                migrations.AddField(
                    model_name='action',
                    name='organization',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='planning.organization', verbose_name='Organisation'),
                ),
                migrations.CreateModel(
                    name='PlanAction',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('titre', models.CharField(max_length=500)),
                        ('impact', models.TextField()),
                        ('annee_debut', models.PositiveIntegerField(default=2025)),
                        ('horizon', models.PositiveIntegerField()),
                        ('couts', models.JSONField(default=list)),
                        ('statut_pao', models.JSONField(default=list)),
                        ('nombre_effets', models.PositiveIntegerField(default=0)),
                        ('nombre_produits', models.PositiveIntegerField(default=0)),
                        ('nombre_actions', models.PositiveIntegerField(default=0)),
                        ('nombre_activites', models.PositiveIntegerField(default=0)),
                        ('reference', models.CharField(blank=True, max_length=50)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='planning.organization', verbose_name='Organisation')),
                    ],
                    options={
                        'verbose_name': "Plan d'actions",
                        'verbose_name_plural': "Plans d'actions",
                    },
                ),
                migrations.CreateModel(
                    name='Effet',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('titre', models.CharField(max_length=500)),
                        ('couts', models.JSONField(default=list)),
                        ('nombre_produits', models.PositiveIntegerField(default=0)),
                        ('nombre_actions', models.PositiveIntegerField(default=0)),
                        ('nombre_activites', models.PositiveIntegerField(default=0)),
                        ('reference', models.CharField(blank=True, max_length=50)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='planning.organization', verbose_name='Organisation')),
                        ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_effet', to='planning.planaction')),
                    ],
                    options={
                        'verbose_name': 'Effet',
                        'verbose_name_plural': 'Effets',
                    },
                ),
                migrations.CreateModel(
                    name='Produit',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('titre', models.CharField(max_length=500)),
                        ('couts', models.JSONField(default=list)),
                        ('nombre_actions', models.PositiveIntegerField(default=0)),
                        ('nombre_activites', models.PositiveIntegerField(default=0)),
                        ('reference', models.CharField(blank=True, max_length=50)),
                        ('effet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effet_produit', to='planning.effet')),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='planning.organization', verbose_name='Organisation')),
                    ],
                    options={
                        'verbose_name': 'Produit',
                        'verbose_name_plural': 'Produits',
                    },
                ),
                migrations.AddField(
                    model_name='action',
                    name='produit',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_action', to='planning.produit'),
                ),
                migrations.CreateModel(
                    name='TrainingCourse',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=500)),
                        ('description', models.TextField(blank=True)),
                        ('duration_hours', models.PositiveIntegerField(default=0)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='planning.organization', verbose_name='Organisation')),
                    ],
                    options={
                        'verbose_name': 'Formation',
                        'verbose_name_plural': 'Formations',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='Certification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='planning.organization', verbose_name='Organisation')),
                        ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='planning.trainingcourse')),
                    ],
                    options={
                        'verbose_name': 'Certification',
                        'verbose_name_plural': 'Certifications',
                    },
                ),
                migrations.CreateModel(
                    name='OrganizationUser',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('role', models.CharField(choices=[('admin_org', 'Administrateur organisation'), ('expert', 'Expert'), ('reader', 'Utilisateur lecture'), ('trainer', 'Formateur')], default='reader', max_length=20, verbose_name='Rôle SaaS')),
                        ('is_admin', models.BooleanField(default=False, help_text='Donne les mêmes droits que le rôle admin_org', verbose_name='Admin organisation')),
                        ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                        ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='planning.organization', verbose_name='Organisation')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                    ],
                    options={
                        'verbose_name': 'Membre organisation',
                        'verbose_name_plural': 'Membres organisations',
                        'ordering': ['-is_admin', 'role', 'user__email'],
                        'unique_together': {('user', 'organization')},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
