# Generated by Django 5.1.2 on 2026-07-03 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_seed_dpse_organization'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='StrategicPlan',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=500)),
                        ('description', models.TextField(blank=True)),
                        ('start_year', models.PositiveIntegerField(default=2025)),
                        ('horizon', models.PositiveIntegerField(default=5)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='planning.organization', verbose_name='Organisation')),
                    ],
                    options={
                        'verbose_name': 'Plan stratégique',
                        'verbose_name_plural': 'Plans stratégiques',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='StrategicAxis',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('axis_type', models.CharField(choices=[('governance', 'Gouvernance'), ('attributes', 'Attributs'), ('results', 'Résultats')], max_length=20)),
                        ('weight', models.PositiveIntegerField(default=1)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='planning.organization', verbose_name='Organisation')),
                        ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='planning.strategicplan')),
                    ],
                    options={
                        'verbose_name': 'Axe stratégique',
                        'verbose_name_plural': 'Axes stratégiques',
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL("ALTER TABLE strategy_strategicplan RENAME TO planning_strategicplan;"),
                migrations.RunSQL("ALTER TABLE strategy_strategicaxis RENAME TO planning_strategicaxis;"),
            ],
        ),
    ]
