# Generated by Django 5.1.2 on 2026-07-21 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_strategy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanActionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('createur', 'Créateur'), ('participant', 'Participant')], default='participant', max_length=20, verbose_name='Rôle')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Invité le')),
                ('plan_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='planning.planaction', verbose_name="Plan d'action")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Membre du plan d'action",
                'verbose_name_plural': "Membres des plans d'action",
                'unique_together': {('user', 'plan_action')},
            },
        ),
    ]
