# Generated by Django 5.1.2 on 2026-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_planactionmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planactionmember',
            name='role',
            field=models.CharField(choices=[('createur', 'Créateur'), ('suiveur_evaluateur', 'Suiveur Évaluateur'), ('point_focal', 'Point Focal'), ('responsable', 'Responsable'), ('participant', 'Participant')], default='participant', max_length=20, verbose_name='Rôle dans le PA'),
        ),
    ]
