# Generated by Django 5.1.2 on 2026-07-22 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_planactionmember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='planactionmember',
            name='role',
            field=models.CharField(choices=[('suiveur_evaluateur', 'Suiveur Évaluateur'), ('point_focal', 'Point Focal'), ('responsable', 'Responsable'), ('participant', 'Participant')], default='participant', max_length=20, verbose_name='Rôle dans le PA'),
        ),
    ]
