# Generated by Django 5.1.2 on 2026-07-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_planaction_created_by_alter_planactionmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planactionmember',
            name='role',
            field=models.CharField(choices=[('point_focal', 'Point Focal'), ('responsable', 'Responsable'), ('participant', 'Participant')], default='participant', max_length=20, verbose_name='Rôle dans le PA'),
        ),
    ]
